### PR TITLE
on osx, install curl using brew

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Review by xSavitar — COMMENTED** [review]
LGTM! The command for installing brew is valid but the only issue could be if `brew` itself is not installed (as it doesn't come in-built in osx) but it is, this works just great. Thanks :)

**Comment by andy5995** [comment]
You're welcome.

This is what's installed:

https://github.com/actions/virtual-environments/blob/macOS-10.15/20210531.1/images/macos/macos-10.15-Readme.md

Maybe you could use vcpkg to install curl on the Windows test build?

**Comment by andy5995** [comment]
> You're welcome.
> 
> This is what's installed:
> 
> https://github.com/actions/virtual-environments/blob/macOS-10.15/20210531.1/images/macos/macos-10.15-Readme.md
> 
> Maybe you could use vcpkg to install curl on the Windows test build?

I just noticed under the [Utilities](https://github.com/actions/virtual-environments/blob/macOS-10.15/20210531.1/images/macos/macos-10.15-Readme.md#utilities) section that curl is already installed.

**Review by stephenmathieson — APPROVED** [review]
Thanks!

**Comment by stephenmathieson** [comment]
Tests failed on the `master` branch: https://github.com/clibs/clib/runs/2823085469. I don't think this works

**Comment by andy5995** [comment]
https://github.com/clibs/clib/runs/2823085469#step:4:141

That looks related to #237

**Pull request merged**
