### PR TITLE
feature: first implementation of clib-init.

### PR DESCRIPTION
**Pull request by diasbruno**
This is a first implementation for `clib-init`.

### CODE REVIEW

**Comment by jwerle** [comment]
@diasbruno what are your thoughts on supporting a `clib.json` here through some command line argument? re: #85

**Comment by diasbruno** [comment]
@jwerle Looks good. Which one should be the default (`package`or `clib`)? What are good names for this (`--use-package` and `--use-clib` or `--file clib.json`)?

**Comment by jwerle** [comment]
@diasbruno I'm open to suggestions! Maybe `--manifest clib.json` to override the file name for now until we have support for `clib.json` elsewhere

**Comment by diasbruno** [comment]
Done, @jwerle. Thanks for helping me with this.

**Pull request merged**
