### PR TITLE
update wiki registry.

### PR DESCRIPTION
**Pull request by diasbruno**

### CODE REVIEW

**Comment by diasbruno** [comment]
There is also a bug on the caching mechanism. Deleting the cache causes a segfault.

**Comment by diasbruno** [comment]
https://github.com/clibs/wiki-registry.c/pull/7 fixes the issue on linux.

**Review by stephenmathieson — COMMENTED** [review]
Thanks! Can you bump the wiki-registry version to 0.1.2?

**Comment by diasbruno** [comment]
Done, @stephenmathieson.

**Pull request merged**
