### PR TITLE
feat(src/clib-install.c): Support 'clib.json'

### PR DESCRIPTION
**Pull request by jwerle**
See #85

### CODE REVIEW

**Comment by jwerle** [comment]
cc @yorkie @stephenmathieson

**Comment by diasbruno** [comment]
@jwerle Long time ago, I started to implement a cache mechanism for clib. 
[diasbruno/clib-download](https://github.com/diasbruno/clib-download)
Let me know if we can revive this repo, or, it can be dropped.

**Comment by jwerle** [comment]
Yeah! Happy to start a conversation around it

**Comment by Isty001** [comment]
I don't know if it's any help, but I also did that, and actually implemented a fully working cache for clib. https://github.com/clibs/clib-cache

But it has been suggested to migrate clib-package and the cache into the main repo as it has no benefit to keep the separately, there is a PR that does that, but unfortunately I had no time back then to complete the review comments, and then forgot it. https://github.com/clibs/clib/pull/146

**Comment by jwerle** [comment]
would love to merge this today :wink:  :upside_down_face:

**Comment by diasbruno** [comment]
@Isty001 Looks great. Mine is far behind both, so I think I'll archive it or see if it fits other purpose.
@jwerle Let me know if there is something I can help.

**Pull request merged**
