### PR TITLE
Implement building multithreaded for windows.

### PR DESCRIPTION
**Pull request by nouwaarom**
I think that it should be possible to make the windows builds multi threaded as well.

### CODE REVIEW

**Review by jwerle — APPROVED** [review]
LGTM

**Comment by jwerle** [comment]
cc @Isty001 @stephenmathieson

**Comment by nouwaarom** [comment]
Do you know what happened to the macOS tests? It seems like they got stuck

**Comment by jwerle** [comment]
> Do you know what happened to the macOS tests? It seems like they got stuck

Not sure but we can address in isolation in a separate PR

**Comment by Isty001** [comment]
> Do you know what happened to the macOS tests? It seems like they got stuck

Unfortunately the MacOS tests are failing for a while now #237 
I couldn't find out why, and I have no access to a mac machine.

**Comment by jwerle** [comment]
> > Do you know what happened to the macOS tests? It seems like they got stuck
> 
> Unfortunately the MacOS tests are failing for a while now #237 I couldn't find out why, and I have no access to a mac machine.

Same here :(

**Comment by jwerle** [comment]
@nouwaarom we can merge this PR as is, for now

**Pull request merged**
