### PR TITLE
Add 'curl-config' to Makefile to find cURL

### PR DESCRIPTION
**Pull request by zbrdge**
I needed this change to get clib to compile under FreeBSD, where I had installed libcurl via pkgng. I'm not sure as I haven't tested on other platforms yet but apparently this was added in curl 7.7.2 (http://curl.haxx.se/libcurl/using/) and should be available with most libcurl installations.

Perhaps there's a better way to do this if it is desired to support older versions of libcurl?

### CODE REVIEW

**Comment by jwerle** [comment]
+1

@stephenmathieson we've had many issues with curl in the past for various projects. This LGTM, but what do you think?

**Comment by stephenmathieson** [comment]
this seems reasonable to me.  any idea how this effects windows users?

/cc @mattn

**Comment by mattn** [comment]
You need to remove `-lcurl` in whole part. And this is no longer to keep Windows_NT part. Let's clean-up like [this](https://gist.github.com/mattn/497c71960e85efa34bec) :+1:

**Comment by jwerle** [comment]
@zbrdge care to make the changes @mattn proposed ?

**Comment by zbrdge** [comment]
Ok changes made per @mattn's suggestion and tested on my FreeBSD box here.

**Comment by jwerle** [comment]
@zbrdge could you update your branch with master so we can merge ?

**Comment by zbrdge** [comment]
So I just merged master into my branch - looks like you may actually need me to rebase on top? Or perhaps not. Let me know and I'll make it happen.

**Comment by jwerle** [comment]
@zbrdge sorry for the delay here. We can now "Squash and merge" in a PR

**Pull request merged**
