### PR TITLE
Notifying the user if new version is available 

### PR DESCRIPTION
**Pull request by Isty001**
The PR is the implementation of #213

### CODE REVIEW

**Review by jwerle — APPROVED** [review]

**Comment by jwerle** [comment]
looks good!

```sh
 √ clib --version
        info : You are using clib 2.3.0, a new version is avalable. You can upgrade with the following command: clib upgrade --tag 2.4.0
2.3.0

```

**Comment by Isty001** [comment]
Thanks for testing! :tada: 

Meanwhile I forgot to update `CLIB_VERSION`, so already created a patch for that version. :smile:

**Comment by jwerle** [comment]
oops yeah that makes sense why I am seeing `2.3.0`

**Comment by Isty001** [comment]
Yeah sorry about that, I checked it, and it should be fixed now. :(

**Comment by jwerle** [comment]
hell yeah!

**Comment by stephenmathieson** [comment]
Awesome, well done @Isty001!

**Pull request merged**
